### ISSUE TITLE
vant的外部样式类无法使用

### ISSUE THREAD

**Issue by dxwb** [F-loat/mpvue-quickstart#18]
# 用vant的组件的外部样式类没有作用
``` html
<van-cell :border="false" custom-class="van-cell-custom">
  <div slot="icon">颜色</div>
  <div slot="title">
    asd
  </div>
</van-cell>
```
样式类
``` css
.van-cell-custom{
  padding: 0;
}
```
这样写发现没有作用，然后我看了一下编译后的css，结果变成了
``` css
.van-cell-custom.data-v-5052fdb2 {
  padding: 0;
}
```
但是这个组件相应的节点并没有加上.data-v-5052fdb2，所以选择器没有选中元素，有什么办法解决吗
